const handleCaughtError = () => {

    throw new Error('Fatal error');
}

export {
    handleCaughtError,
}
